/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface": "#f7faf8",
        "surface-bright": "#f7faf8",
        "surface-dim": "#d7dbd9",
        "surface-tint": "#006a63",
        "surface-variant": "#e0e3e1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f3",
        "surface-container": "#ebefed",
        "surface-container-high": "#e5e9e7",
        "surface-container-highest": "#e0e3e1",
        "on-surface": "#181c1c",
        "on-surface-variant": "#3e4947",
        "background": "#f7faf8",
        "on-background": "#181c1c",
        "primary": "#005c55",
        "on-primary": "#ffffff",
        "primary-container": "#0f766e",
        "on-primary-container": "#a3faef",
        "primary-fixed": "#9cf2e8",
        "primary-fixed-dim": "#80d5cb",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#00504a",
        "inverse-primary": "#80d5cb",
        "secondary": "#625e59",
        "on-secondary": "#ffffff",
        "secondary-container": "#e5ded8",
        "on-secondary-container": "#66625d",
        "secondary-fixed": "#e8e1db",
        "secondary-fixed-dim": "#ccc5bf",
        "on-secondary-fixed": "#1e1b17",
        "on-secondary-fixed-variant": "#4a4641",
        "tertiary": "#7f4025",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9c573a",
        "on-tertiary-container": "#ffe5db",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb598",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#72361b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "outline": "#6e7977",
        "outline-variant": "#bdc9c6",
        "inverse-surface": "#2d3130",
        "inverse-on-surface": "#eef1f0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gap: "16px",
        container_margin: "32px",
        card_padding: "24px",
        base: "8px",
      },
      fontFamily: {
        h1: ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        "vital-lg": ["JetBrains Mono", "monospace"],
        "vital-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        h1: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        body: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        label: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "vital-lg": ["20px", { lineHeight: "24px", fontWeight: "600" }],
        "vital-sm": ["14px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
